Mustard.Application/Controllers/CultureController.cs
using System.Web.Mvc;

namespace Mustard.Application.Controllers
{
  public class CultureController : BaseController
  {
    public ActionResult ChangeLocale(string returnUrl)
    {
      Session["culture"] = CurrentCulture == "ru-RU" ? "en-US" : "ru-RU";

      if (Url.IsLocalUrl(returnUrl))
      {
        return Redirect(returnUrl);
      }

      return RedirectToAction("Index", "Home");
    }
  }
}

Mustard.Application/Views/Shared/AccessNotAllowed.cshtml
@{
    ViewBag.Title = Res.AccessNotAllowed;
}

<h2>@Res.AccessNotAllowed</h2>

Mustard.Application/Views/Shared/_CulturePartial.cshtml
  @using (Html.BeginForm("ChangeLocale", "Culture", FormMethod.Post, new {id = "cultureForm", @class = "navbar-right"}))
  {
    @Html.Hidden("returnUrl", Request.RawUrl)

    bool isRussian = (string) Session["culture"] == "ru-RU";
    <a href="javascript:document.getElementById('cultureForm').submit()">@(isRussian ? "English" : "Русский")</a>

    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="javascript:document.getElementById('cultureForm').submit()">@(isRussian ? "English" : "Русский")</a>
      </li>
    </ul>
  }

Mustard.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mustard PROJECTS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          @Html.ActionLink("Mustard PROJECTS", "Index", "Home", null, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>@Html.ActionLink(Res.HomeLink, "Index", "Home")</li>
          </ul>
          @Html.Partial("_CulturePartial")
          @Html.Partial("_LoginPartial")
        </div>
      </div>
    </div>
    <div class="container body-content">
      @RenderBody()
      <hr />
      <footer>
        <p>&copy; @DateTime.Now.Year - Mustard PROJECTS</p>
      </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
  </body>
</html>